//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketToRideGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicketToRideGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string btnCloseLostGame {
            get {
                return ResourceManager.GetString("btnCloseLostGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Sala.
        /// </summary>
        public static string btnCreateLobbie {
            get {
                return ResourceManager.GetString("btnCreateLobbie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar.
        /// </summary>
        public static string btnGoBackRegistration {
            get {
                return ResourceManager.GetString("btnGoBackRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        public static string btnGoRegistration {
            get {
                return ResourceManager.GetString("btnGoRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Qué inicie la aventura!.
        /// </summary>
        public static string btnGoToLogin {
            get {
                return ResourceManager.GetString("btnGoToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dentro Estacion .
        /// </summary>
        public static string btnLoginRegistration {
            get {
                return ResourceManager.GetString("btnLoginRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        public static string btnLogOut {
            get {
                return ResourceManager.GetString("btnLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugar.
        /// </summary>
        public static string btnPlayGame {
            get {
                return ResourceManager.GetString("btnPlayGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir a mi perfil.
        /// </summary>
        public static string btnProfileMenu {
            get {
                return ResourceManager.GetString("btnProfileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir de menú principal.
        /// </summary>
        public static string btnReturnToTheMainMenu {
            get {
                return ResourceManager.GetString("btnReturnToTheMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Ups!, problemas en el callback.
        /// </summary>
        public static string CallbackProblem {
            get {
                return ResourceManager.GetString("CallbackProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una capacidad..
        /// </summary>
        public static string CapacityRoom {
            get {
                return ResourceManager.GetString("CapacityRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Ups!, algo falló con tu conexión, intentalo nuevamente.
        /// </summary>
        public static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puedes tomar cartas del mazos.
        /// </summary>
        public static string DontTakeCards {
            get {
                return ResourceManager.GetString("DontTakeCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo proporcionado no es admitido, revise que cumpla con un dominio correcto y que no exista espacios en blanco entre caracteres.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puedes seleccionar casillas vacías.
        /// </summary>
        public static string EmptyBoxes {
            get {
                return ResourceManager.GetString("EmptyBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error al crear el lobby, por favor intentelo más tarde.
        /// </summary>
        public static string ErrorCreatingRoom {
            get {
                return ResourceManager.GetString("ErrorCreatingRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al entrar a la sala.
        /// </summary>
        public static string ErrorEnteringRoom {
            get {
                return ResourceManager.GetString("ErrorEnteringRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Gamertag ya se encuentra registrado.
        /// </summary>
        public static string ExistingGamertag {
            get {
                return ResourceManager.GetString("ExistingGamertag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo ya se encuentra registrado.
        /// </summary>
        public static string ExistingMail {
            get {
                return ResourceManager.GetString("ExistingMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al procesar la solicitud de amistad.
        /// </summary>
        public static string FailedFriendshipRequest {
            get {
                return ResourceManager.GetString("FailedFriendshipRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al tratar de restablecer la contraseña, intentelo más tarde.
        /// </summary>
        public static string FailedPassword {
            get {
                return ResourceManager.GetString("FailedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La sala a la que tratas de unirte se encuentra llena.
        /// </summary>
        public static string FullRoom {
            get {
                return ResourceManager.GetString("FullRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Gamertag ingresado ya se encuentra en uso..
        /// </summary>
        public static string GamertagDuplicate {
            get {
                return ResourceManager.GetString("GamertagDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El anfitrión ha abandonado la sala.
        /// </summary>
        public static string HostAbandonedRoom {
            get {
                return ResourceManager.GetString("HostAbandonedRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique la clave del lobby, la clave ingresada es incorrecta.
        /// </summary>
        public static string IncorrectLobbyPassword {
            get {
                return ResourceManager.GetString("IncorrectLobbyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. Tenemos un problema para iniciar.
        /// </summary>
        public static string InopportuneResponse {
            get {
                return ResourceManager.GetString("InopportuneResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, recuerda utilizar caracteres alfanuméricos.
        /// </summary>
        public static string InvalidGamertag {
            get {
                return ResourceManager.GetString("InvalidGamertag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre debe ir solo con letras, no con simbolos ni numeros y debe ser de almenos una extensión de 8 caracteres.
        /// </summary>
        public static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña ingresada no cumple con los caracteres de seguridad, por favor ingrese una contraseña robusta.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario inválido.
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Quieres que sea tu amigo.
        /// </summary>
        public static string InviteFriend {
            get {
                return ResourceManager.GetString("InviteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amigos.
        /// </summary>
        public static string lblFriends {
            get {
                return ResourceManager.GetString("lblFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        public static string lblRegistration {
            get {
                return ResourceManager.GetString("lblRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar sala.
        /// </summary>
        public static string lblSearchRoom {
            get {
                return ResourceManager.GetString("lblSearchRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo ingresado no se encontró dentro del juego.
        /// </summary>
        public static string MailNonexistent {
            get {
                return ResourceManager.GetString("MailNonexistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubo un error al enviar el correo, te recomendamos intentarlo más tarde.
        /// </summary>
        public static string MailSendingError {
            get {
                return ResourceManager.GetString("MailSendingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se a restablecido la contraseña  correctamente.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El jugador ha sido invitado :).
        /// </summary>
        public static string PlayerGuest {
            get {
                return ResourceManager.GetString("PlayerGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro no ha sido posible, inténtelo más tarde.
        /// </summary>
        public static string PlayerNotRegistered {
            get {
                return ResourceManager.GetString("PlayerNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este jugador al que tratas de invitar ya es tu amigo o ya se le envió solicitud.
        /// </summary>
        public static string RepeatedFriendshipRequest {
            get {
                return ResourceManager.GetString("RepeatedFriendshipRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha enviado un correo con una clave unica para establecer una nueva contraseña.
        /// </summary>
        public static string RestorePassword {
            get {
                return ResourceManager.GetString("RestorePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La sala a la que tratas de unirte ya no está disponible.
        /// </summary>
        public static string RoomNotAvailable {
            get {
                return ResourceManager.GetString("RoomNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servidor no está disponible por el momento. Por favor, inténtelo más tarde.
        /// </summary>
        public static string ServerNotAvailable {
            get {
                return ResourceManager.GetString("ServerNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha enviado con éxito la solicitud de amistad.
        /// </summary>
        public static string SuccessfulFriendshipRequest {
            get {
                return ResourceManager.GetString("SuccessfulFriendshipRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro exitoso.
        /// </summary>
        public static string SuccessfullyRegisteredPlayer {
            get {
                return ResourceManager.GetString("SuccessfullyRegisteredPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal,.
        /// </summary>
        public static string txbLostMessage {
            get {
                return ResourceManager.GetString("txbLostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perdiste.
        /// </summary>
        public static string txbLostMessage02 {
            get {
                return ResourceManager.GetString("txbLostMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felicidades.
        /// </summary>
        public static string txbWonMessage {
            get {
                return ResourceManager.GetString("txbWonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string txtEmailRegistration {
            get {
                return ResourceManager.GetString("txtEmailRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string txtGamerTagRegistration {
            get {
                return ResourceManager.GetString("txtGamerTagRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partidas jugadas.
        /// </summary>
        public static string txtGamesPlayed {
            get {
                return ResourceManager.GetString("txtGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partidas ganadas.
        /// </summary>
        public static string txtGamesWon {
            get {
                return ResourceManager.GetString("txtGamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string txtNameRegistration {
            get {
                return ResourceManager.GetString("txtNameRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string txtPasswordRegistration {
            get {
                return ResourceManager.GetString("txtPasswordRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Jugador.
        /// </summary>
        public static string txtPlayerId {
            get {
                return ResourceManager.GetString("txtPlayerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string txtProfile {
            get {
                return ResourceManager.GetString("txtProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estadisticas.
        /// </summary>
        public static string txtScore {
            get {
                return ResourceManager.GetString("txtScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentaje de victorias.
        /// </summary>
        public static string txtWinningPercentage {
            get {
                return ResourceManager.GetString("txtWinningPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifica el código enviado al correo que proporcionaste.
        /// </summary>
        public static string VerifyCode {
            get {
                return ResourceManager.GetString("VerifyCode", resourceCulture);
            }
        }
    }
}
